// Problem: 10415 - Eb Alto Saxophone Player
// Contest: UVa Online Judge
// URL: https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=24&page=show_problem&problem=1356
// Memory Limit: 32 MB
// Time Limit: 3000 ms
// 
// Powered by CP Editor (https://cpeditor.org)
#include <iostream>
using namespace std;

int fin[10]={0,0,0,0,0,0,0,0,0,0},stat[10]={0,0,0,0,0,0,0,0,0,0};

int main(){
	int n,ni,i;
	string song;
	cin>>n;
	getline(cin,song);
	for(ni=1;ni<=n;ni++){
		getline(cin,song);
		if(song.size()==0){
			cout<<"0 0 0 0 0 0 0 0 0 0"<<endl;
			continue;
		}
		for(i=0;i<song.size();i++){
			if(song[i]=='c'){
				if(fin[0]==1){
					fin[0]=0;
				}
				if(fin[1]==0){
					fin[1]=1;
					stat[1]+=1;
				}
				if(fin[2]==0){
					fin[2]=1;
					stat[2]+=1;
				}
				if(fin[3]==0){
					fin[3]=1;
					stat[3]+=1;
				}
				if(fin[6]==0){
					fin[6]=1;
					stat[6]+=1;
				}
				if(fin[7]==0){
					fin[7]=1;
					stat[7]+=1;
				}
				if(fin[8]==0){
					fin[8]=1;
					stat[8]+=1;
				}
				if(fin[9]==0){
					fin[9]=1;
					stat[9]+=1;
				}
				continue;
			}
			if(song[i]=='C'){
				if(fin[0]==1){
					fin[0]=0;
				}
				if(fin[1]==1){
					fin[1]=0;
				}
				if(fin[2]==0){
					fin[2]=1;
					stat[2]+=1;
				}
				if(fin[3]==1){
					fin[3]=0;
				}
				if(fin[6]==1){
					fin[6]=0;
				}
				if(fin[7]==1){
					fin[7]=0;
				}
				if(fin[8]==1){
					fin[8]=0;
				}
				if(fin[9]==1){
					fin[9]=0;
				}
				continue;
			}
			if(song[i]>='a'&&song[i]<='g'){
				if(fin[0]==1){
					fin[0]=0;
				}
			}
			if(song[i]>='A'&&song[i]<='G'){
				if(fin[0]==0){
					fin[0]=1;
					stat[0]+=1;
				}
				song[i]=char(int(song[i])-'A'+'a');
			}
			if(song[i]=='d'){
				if(fin[1]==0){
					fin[1]=1;
					stat[1]+=1;
				}
				if(fin[2]==0){
					fin[2]=1;
					stat[2]+=1;
				}
				if(fin[3]==0){
					fin[3]=1;
					stat[3]+=1;
				}
				if(fin[6]==0){
					fin[6]=1;
					stat[6]+=1;
				}
				if(fin[7]==0){
					fin[7]=1;
					stat[7]+=1;
				}
				if(fin[8]==0){
					fin[8]=1;
					stat[8]+=1;
				}
				if(fin[9]==1){
					fin[9]=0;
				}
			}
			if(song[i]=='e'){
				if(fin[1]==0){
					fin[1]=1;
					stat[1]+=1;
				}
				if(fin[2]==0){
					fin[2]=1;
					stat[2]+=1;
				}
				if(fin[3]==0){
					fin[3]=1;
					stat[3]+=1;
				}
				if(fin[6]==0){
					fin[6]=1;
					stat[6]+=1;
				}
				if(fin[7]==0){
					fin[7]=1;
					stat[7]+=1;
				}
				if(fin[8]==1){
					fin[8]=0;
				}
				if(fin[9]==1){
					fin[9]=0;
				}
			}
			if(song[i]=='f'){
				if(fin[1]==0){
					fin[1]=1;
					stat[1]+=1;
				}
				if(fin[2]==0){
					fin[2]=1;
					stat[2]+=1;
				}
				if(fin[3]==0){
					fin[3]=1;
					stat[3]+=1;
				}
				if(fin[6]==0){
					fin[6]=1;
					stat[6]+=1;
				}
				if(fin[7]==1){
					fin[7]=0;
				}
				if(fin[8]==1){
					fin[8]=0;
				}
				if(fin[9]==1){
					fin[9]=0;
				}
			}
			if(song[i]=='g'){
				if(fin[1]==0){
					fin[1]=1;
					stat[1]+=1;
				}
				if(fin[2]==0){
					fin[2]=1;
					stat[2]+=1;
				}
				if(fin[3]==0){
					fin[3]=1;
					stat[3]+=1;
				}
				if(fin[6]==1){
					fin[6]=0;
				}
				if(fin[7]==1){
					fin[7]=0;
				}
				if(fin[8]==1){
					fin[8]=0;
				}
				if(fin[9]==1){
					fin[9]=0;
				}				
			}
			if(song[i]=='a'){
				if(fin[1]==0){
					fin[1]=1;
					stat[1]+=1;
				}
				if(fin[2]==0){
					fin[2]=1;
					stat[2]+=1;
				}
				if(fin[3]==1){
					fin[3]=0;
				}
				if(fin[6]==1){
					fin[6]=0;
				}
				if(fin[7]==1){
					fin[7]=0;
				}
				if(fin[8]==1){
					fin[8]=0;
				}
				if(fin[9]==1){
					fin[9]=0;
				}
			}
			if(song[i]=='b'){
				if(fin[1]==0){
					fin[1]=1;
					stat[1]+=1;
				}
				if(fin[2]==1){
					fin[2]=0;
				}
				if(fin[3]==1){
					fin[3]=0;
				}
				if(fin[6]==1){
					fin[6]=0;
				}
				if(fin[7]==1){
					fin[7]=0;
				}
				if(fin[8]==1){
					fin[8]=0;
				}
				if(fin[9]==1){
					fin[9]=0;
				}	
			}
		}
		for(i=0;i<9;i++){
			cout<<stat[i]<<" ";
			fin[i]=0;
			stat[i]=0;
		}
		cout<<stat[9];
		fin[9]=0;
		stat[9]=0;
		cout<<endl;
	}
	return 0;
}
